### ISSUE TITLE
2023 May 17 - Technical Steering Committee Meeting Agenda

### ISSUE THREAD

**Issue by TheJuanAndOnly99** [finos/technical-steering-committee#63]
## Date
2023 May 17th - 12:00PM EST / 17:00 BST

### Zoom Info
- Meeting link: https://zoom.us/j/93181085065
- Meeting number: 931 8108 5065
- Password: Check the email invite
- Call-in: Find your local number [https://zoom.us/u/abk6zPS0y5](https://www.google.com/url?q=https://zoom.us/u/abk6zPS0y5&sa=D&source=calendar&ust=1683993619379903&usg=AOvVaw1_TLXlYEn-o_TCgxFKLIXX)

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes (done via #62)
- [x] Discuss the TSC responsibilities https://github.com/finos/technical-steering-committee/pull/64
- [x] Update on Project Activations 
  - [x] [Morphir](https://github.com/finos/community/issues/230) - update from @eminty69 
  - [x] [Spring Bot](https://github.com/finos/community/issues/236) - update from @brunodom 
- [x] All consider whether we need a vice-chair
- [x] All discuss potential in-person meeting at the London Members meeting
- [x] New SIG proposal: [Architecture as Code](https://github.com/finos/community/issues/260) - @maoo 
- [x] Consider suggestion from @caradelia that we meet fortnightly for 30mins. 
- [x] Update on archived projects from @TheJuanAndOnly99 
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes
- [ ] ...
- [ ] ...
- [ ] ...

## Action Items
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by ColinEberhardt** [comment]
@TheJuanAndOnly99 I see you've added a Zenith SIG item to the agenda, can you please elaborate? Who is leading this discussion and what is the ask?

**Comment by ColinEberhardt** [comment]
@maoo thanks for adding the Architecture as Code SIG proposal to the agenda. Do you have a specific ask of the TSC? I just want to point out that previously we determined SIG approval sits with the GB:

https://github.com/finos/technical-steering-committee/blob/b0bad64ff6b76ced047f541f3a5ef372e9c376d8/meetings/2023-03-15.md?plain=1#L26

However, we'd be more than happy to provide general input and feedback.

**Comment by maoo** [comment]
@ColinEberhardt - thanks for the comment! I wanted to circulate the SIG proposal to the TSC as an FYI, as it may be of interest at least to some of TSC members, and could fast-track the socialisation process.

**Comment by TheJuanAndOnly99** [comment]
> @TheJuanAndOnly99 I see you've added a Zenith SIG item to the agenda, can you please elaborate? Who is leading this discussion and what is the ask?

we can remove this from the agenda @ColinEberhardt

**Comment by ColinEberhardt** [comment]
@ColinEberhardt / Scott Logic

**Comment by maoo** [comment]
@maoo / FINOS

**Comment by eminty69** [comment]
Elspeth Minty / RBC

**Comment by TheJuanAndOnly99** [comment]
@TheJuanAndOnly99 / FINOS

**Comment by jonfreedman** [comment]
@jonfreedman

I was there for the first few minutes and the last 15... Something urgent came up in between

**Comment by ColinEberhardt** [comment]
Meeting minutes can be found here https://github.com/finos/technical-steering-committee/pull/65
